'use client'

import { useState, useRef, useEffect, useCallback } from 'react'
import { useTranslation } from 'react-i18next'
import { ChevronsLeftRight, Keyboard } from 'lucide-react'
import { useScrollAnimation } from '@/hooks/useScrollAnimation'
import { AnimatedSection } from '@/components/ui/AnimatedCard'

interface BeforeAfterCase {
  id: string
  titleKey: string
  descriptionKey: string
  /**
   * Реальні клінічні фото «до/після» одного пацієнта (за згодою) кладуться в
   * public/assets/images/before-after/. Поки їх немає — рендериться брендовий
   * плейсхолдер-слот; інтер'єри більше не видаються за клінічні результати (18).
   */
  beforeImage?: string
  afterImage?: string
  treatmentKey: string
  durationKey: string
}

// Seven cases mirroring the clinic's flagship services (veneers, implants,
// braces, whitening, composite restoration, zirconia crowns, hygiene).
// Until the clinic can share consented clinical photos, the slider runs on
// branded vector illustrations generated by scripts/gen-before-after-cases.mjs
// (before-after-assets.test.ts pins them to the generator). The section copy
// explicitly calls them illustrative examples — swapping in real photos is a
// path change here plus regenerating nothing.
// Keys are built from the id, so the static-literal i18n guard can't see
// them — before-after-cases-i18n.test.ts iterates this exported array and
// asserts every key resolves in uk/en/pl instead.
// eslint-disable-next-line react-refresh/only-export-components -- data export consumed by the i18n test
export const beforeAfterCases: BeforeAfterCase[] = Array.from(
  { length: 7 },
  (_, i) => {
    const id = String(i + 1)
    return {
      id,
      titleKey: `caseStudies.cases.${id}.title`,
      descriptionKey: `caseStudies.cases.${id}.description`,
      beforeImage: `/assets/images/before-after/case-${id}-before.svg`,
      afterImage: `/assets/images/before-after/case-${id}-after.svg`,
      treatmentKey: `caseStudies.cases.${id}.treatment`,
      durationKey: `caseStudies.cases.${id}.duration`,
    }
  }
)

/** Слот під реальне клінічне фото; поки фото немає — брендовий плейсхолдер. */
function CasePhoto({
  src,
  label,
  className,
}: {
  src?: string
  label: string
  className?: string
}) {
  if (src) {
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img
        src={src}
        alt={label}
        loading="lazy"
        className="absolute inset-0 h-full w-full object-cover"
        draggable={false}
      />
    )
  }
  return (
    <div
      className={`absolute inset-0 flex items-center justify-center bg-dental-secondary-200 p-6 text-center ${className ?? ''}`}
    >
      <span className="text-sm font-medium text-dental-muted">{label}</span>
    </div>
  )
}

/**
 * Слайдер порівняння «до/після» (макет 2a): ручка — фокусована кнопка 48px
 * з role="slider" і aria-valuenow; ←/→ = крок 5%, Home/End = краї;
 * порівняння повністю доступне з клавіатури (закриває 19). Drag/touch
 * лишаються для миші.
 */
function ComparisonSlider({
  beforeImage,
  afterImage,
  beforeLabel,
  afterLabel,
  t,
}: {
  beforeImage?: string
  afterImage?: string
  beforeLabel: string
  afterLabel: string
  t: (key: string, opts?: Record<string, unknown>) => string
}) {
  const [position, setPosition] = useState(55)
  const [isDragging, setIsDragging] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)

  const moveTo = useCallback((clientX: number) => {
    if (!containerRef.current) return
    const rect = containerRef.current.getBoundingClientRect()
    // Layout race (e.g. dragging during an entrance transition) can yield a
    // zero-width rect → NaN position; bail so aria-valuenow/width stay valid.
    if (!rect.width) return
    const pct = ((clientX - rect.left) / rect.width) * 100
    setPosition(Math.min(Math.max(pct, 0), 100))
  }, [])

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
      e.preventDefault()
      setPosition(p => Math.max(0, p - 5))
    } else if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
      e.preventDefault()
      setPosition(p => Math.min(100, p + 5))
    } else if (e.key === 'Home') {
      e.preventDefault()
      setPosition(0)
    } else if (e.key === 'End') {
      e.preventDefault()
      setPosition(100)
    }
  }

  useEffect(() => {
    if (!isDragging) return
    const onMove = (e: MouseEvent) => moveTo(e.clientX)
    const onTouch = (e: TouchEvent) => {
      // Non-passive so we can stop the drag from scrolling the page on touch.
      e.preventDefault()
      moveTo(e.touches[0].clientX)
    }
    const onEnd = () => setIsDragging(false)
    window.addEventListener('mousemove', onMove)
    window.addEventListener('touchmove', onTouch, { passive: false })
    window.addEventListener('mouseup', onEnd)
    window.addEventListener('touchend', onEnd)
    return () => {
      window.removeEventListener('mousemove', onMove)
      window.removeEventListener('touchmove', onTouch)
      window.removeEventListener('mouseup', onEnd)
      window.removeEventListener('touchend', onEnd)
    }
  }, [isDragging, moveTo])

  const rounded = Math.round(position)

  return (
    <div
      ref={containerRef}
      className="relative aspect-3/2 w-full overflow-hidden rounded-xl bg-dental-secondary-200 shadow-soft-lg select-none"
    >
      {/* Фото ПІСЛЯ — на всю ширину знизу */}
      <div className="absolute inset-0">
        <CasePhoto src={afterImage} label={afterLabel} />
        <span className="absolute right-4 top-4 rounded-full bg-white/90 px-3.5 py-1 text-[13px] font-semibold text-dental-dark">
          {t('labels.after')}
        </span>
      </div>

      {/* Фото ДО — обрізане позицією повзунка */}
      <div
        className="absolute inset-0 overflow-hidden"
        style={{ width: `${position}%` }}
      >
        <CasePhoto src={beforeImage} label={beforeLabel} />
        <span className="absolute left-4 top-4 rounded-full bg-dental-dark/85 px-3.5 py-1 text-[13px] font-semibold text-white">
          {t('labels.before')}
        </span>
      </div>

      {/* Роздільник + ручка */}
      <div
        className="pointer-events-none absolute inset-y-0 z-10 w-0.5 -translate-x-1/2 bg-white shadow-[0_0_8px_rgba(0,0,0,0.25)]"
        style={{ left: `${position}%` }}
      >
        <button
          type="button"
          role="slider"
          aria-label={t('caseStudies.sliderAria', { value: rounded })}
          aria-valuemin={0}
          aria-valuemax={100}
          aria-valuenow={rounded}
          aria-valuetext={`${rounded}%`}
          aria-orientation="horizontal"
          onKeyDown={onKeyDown}
          onMouseDown={() => setIsDragging(true)}
          onTouchStart={() => setIsDragging(true)}
          className="pointer-events-auto absolute left-1/2 top-1/2 flex h-12 w-12 -translate-x-1/2 -translate-y-1/2 cursor-ew-resize touch-none items-center justify-center rounded-full bg-white shadow-[0_6px_18px_rgba(20,28,30,0.3)] focus:outline-hidden focus:ring-2 focus:ring-dental-primary-500 focus:ring-offset-2"
        >
          <ChevronsLeftRight className="h-5.5 w-5.5 text-dental-primary-600" />
        </button>
      </div>
    </div>
  )
}

export default function BeforeAfterGallery() {
  const { t } = useTranslation()
  const [activeCase, setActiveCase] = useState(0)
  const { ref, isVisible } = useScrollAnimation()

  const currentCase = beforeAfterCases[activeCase]
  const caseName = t(currentCase.treatmentKey)

  return (
    <section
      ref={ref}
      className="snap-start snap-screen flex flex-col justify-center bg-white py-12"
    >
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <AnimatedSection isVisible={isVisible} className="mb-10 text-center">
          <span className="mb-4 inline-block text-sm font-semibold uppercase tracking-wider text-dental-primary-ink">
            {t('caseStudies.results')}
          </span>
          <h2 className="mb-4 text-4xl font-bold leading-tight text-dental-dark lg:text-5xl">
            {t('caseStudies.beforeAfter')}
          </h2>
          <p className="mx-auto max-w-3xl text-xl leading-relaxed text-dental-muted">
            {t('caseStudies.description')}
          </p>
        </AnimatedSection>

        <AnimatedSection isVisible={isVisible} delay={200}>
          <div className="grid grid-cols-1 items-start gap-8 lg:grid-cols-[1.6fr_1fr]">
            {/* Слайдер + метадані */}
            <div>
              <ComparisonSlider
                beforeImage={currentCase.beforeImage}
                afterImage={currentCase.afterImage}
                beforeLabel={t('caseStudies.beforePlaceholder', {
                  case: caseName,
                })}
                afterLabel={t('caseStudies.afterPlaceholder', {
                  case: caseName,
                })}
                t={t}
              />

              <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
                <div className="flex flex-wrap items-center gap-x-6 gap-y-1 text-[13px] text-dental-muted">
                  <span>
                    {t('caseStudies.procedureType')}:{' '}
                    <strong className="font-semibold text-dental-dark">
                      {caseName}
                    </strong>
                  </span>
                  <span>
                    {t('caseStudies.duration')}:{' '}
                    <strong className="font-semibold text-dental-dark">
                      {t(currentCase.durationKey)}
                    </strong>
                  </span>
                </div>
                <span className="flex items-center gap-1.5 text-xs text-dental-secondary-500">
                  <Keyboard className="h-3.5 w-3.5" aria-hidden="true" />
                  {t('caseStudies.keyboardHint')}
                </span>
              </div>
            </div>

            {/* Список кейсів — активний у бренд-рамці (як вибрані стани анкети) */}
            <div className="flex flex-col gap-3.5">
              {beforeAfterCases.map((c, index) => {
                const active = index === activeCase
                return (
                  <button
                    key={c.id}
                    type="button"
                    onClick={() => setActiveCase(index)}
                    aria-pressed={active}
                    aria-label={`${t('caseStudies.selectCase')}: ${t(c.titleKey)}`}
                    className={`flex items-center gap-3 rounded-[14px] p-3 text-left transition-colors ${
                      active
                        ? 'border-[1.5px] border-dental-primary-600 bg-white'
                        : 'border border-dental-secondary-200 bg-white hover:border-dental-primary-400'
                    }`}
                  >
                    <span
                      aria-hidden="true"
                      className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-[10px] font-heading text-base font-extrabold ${
                        active
                          ? 'bg-dental-primary-600 text-white'
                          : 'bg-status-neutral-100 text-dental-primary-600'
                      }`}
                    >
                      {index + 1}
                    </span>
                    <span className="min-w-0">
                      <span className="block font-semibold text-dental-dark">
                        {t(c.titleKey)}
                      </span>
                      <span className="block truncate text-sm text-dental-muted">
                        {t(c.descriptionKey)}
                      </span>
                    </span>
                  </button>
                )
              })}
            </div>
          </div>
        </AnimatedSection>
      </div>
    </section>
  )
}
